replicaCount: 1

image:
  repository: ifilyaninitmo/auth-server-mega-itmo
  pullPolicy: Always
  tag: main

service:
  type: ClusterIP
  port: 8000

env:
  - name: MONGODB_CONN_STR
    value: "mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb-svc.mongodb.svc.cluster.local:27017/auth?authSource=admin"
  - name: TIMESERVER_URL
    value: "http://time-server-app:8001"

livenessProbe: null
readinessProbe: null

ingress:
  enabled: false
autoscaling:
  enabled: false
